language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: "npm install -g npm && npm cache clean"
script: "npm run-script travis"
